### ISSUE TITLE
attachments with missing stat

### ISSUE THREAD

**Issue by Casualuser0339944** [dar-su/arc9_uplp#8]
![4000_21](https://github.com/user-attachments/assets/b66795b2-5ccd-45fa-b2e9-1070c8e52d2b)
![4000_22](https://github.com/user-attachments/assets/1b118fed-2e70-4a78-b4c3-cf11b28e5e5c)

**Comment by MokaAkashiya85** [comment]
They don't have missing stats, just missing custom stat variables.
The stats do apply, but are not displayed in the list, as they are only applied when the stock is "Extended".
This will be fixed momentarily on Git.

**Comment by Casualuser0339944** [comment]
Thanks for fixing the issue.

**Comment by MokaAkashiya85** [comment]
Fixed as of https://github.com/dar-su/arc9_uplp/commit/507e808a87e3de25ce7bdad46e88e097996eb2c0
